---
- hosts: all
  vars:
    - iTrust_folder: "/home/{{ ansible_user }}/iTrust2-v4"
  tasks: 

  - name: clone iTrust2
    become: true
    git:
        repo: "https://github.com/arpitashekhar/iTrust2-v4.git"
        dest: "{{iTrust_folder}}"
        update: no
        force: yes

  # - name: Install jre8
  #   apt:
  #     name: openjdk-8-jre
  #     state: present
  #     update_cache: yes
  #   become: true

  # - name: Adding Oracle Java Repository
  #   become: true
  #   apt_repository: 
  #     repo: 'ppa:webupd8team/java'

  # - name: Accept Java 8 License
  #   become: true
  #   become_user: root
  #   debconf: 
  #     name: 'oracle-java8-installer' 
  #     question: 'shared/accepted-oracle-license-v1-1' 
  #     value: 'true' 
  #     vtype: 'select'

  # - name: Install Oracle Java 8
  #   become: true
  #   apt: 
  #     name: ['oracle-java8-installer', 'ca-certificates', 'oracle-java8-set-default'] 
  #     state: latest

  - name: Update system
    become: true
    command: apt-get update

  - name: Install java 8
    become: true
    command: apt-get install -y default-jdk  

  - name: Setting MySQL root password before installing
    become: true
    debconf:
      name: mysql-server
      question: mysql-server/root_password
      value: ""
      vtype: password

  - name: Confirm MySQL password before installing
    become: true
    debconf:
      name: mysql-server
      question: mysql-server/root_password_again
      value: ""
      vtype: password

  - name: Install MySql Server
    become: true
    apt: 
      name: ['python3-mysqldb', 'mysql-server', 'python-pymysql']
      state: present
  
  - name: Update the configuration file for mySQL
    copy: 
      src: "/home/{{ansible_user}}/deploy-instances/templates/my.cnf"
      dest: /etc/mysql/my.cnf 
      force: yes
    become: true

  - name: Restart MySQL
    service: 
      name: mysql 
      state: restarted
    become: true

  - name: Install Maven
    become: true
    apt: 
      pkg: 'maven' 
      state: latest 
      update_cache: yes 
      cache_valid_time: 3600

  - name: Run process-test-classes
    become: true
    become_user: root
    shell: mvn process-test-classes
    args:
      chdir: "{{iTrust_folder}}/iTrust2/"
  
  - name: Run test to verify iTrust Build
    become: true
    become_user: root
    shell: mvn clean test verify checkstyle:checkstyle
    args:
      chdir: "{{iTrust_folder}}/iTrust2/"

  - name: Check if iTrust is running in port 8080
    become: true
    become_user: root
    shell: nohup bash -c "sudo mvn jetty:run" &
    args:
      chdir: "{{iTrust_folder}}/iTrust2/"
